name: Deploy frontend app

on:
  push:
    branches: [ "main" ]

env: 
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: build image
        id: build-image
        run: |
          docker build -t my-frontend . 
          echo "image=158565517012.dkr.ecr.eu-central-1.amazonaws.com/technative-playground/my-frontend:latest" >> $GITHUB_OUTPUT
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: tag image
        run: docker tag my-frontend:latest 158565517012.dkr.ecr.eu-central-1.amazonaws.com/technative-playground/my-frontend:latest  
    
      - name: push image
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 158565517012.dkr.ecr.eu-central-1.amazonaws.com    

      - name: push to ecr
        run: docker push 158565517012.dkr.ecr.eu-central-1.amazonaws.com/technative-playground/my-frontend:latest
      
      - name: create a task definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: frontend-task-def
          container-name: my-frontend
          image: ${{ steps.build-image.outputs.image }}